# Generated by Django 2.1.4 on 2018-12-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.IntegerField(max_length=3)),
                ('mobile_no', models.IntegerField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=400)),
            ],
        ),
    ]
