//Module for machine b
module bmodule(input binput,output reg [3:0] boutput);
	// binput is the input given and boutput is the output generated	
	always@(binput) begin
		// 4 bit output generated by b(1 1 1 1), IT CAN BE CHANGED BY THE USER		
		boutput=15;
	end	
endmodule
//Module for machine a
module amodule(input[3:0] ainput,output reg [3:0] aoutput);
	// ainput is the input given and aoutput is the output generated
	always@(ainput) begin
		aoutput=ainput;	
	end	
endmodule



